export const FETCH_LOTTERY = 'FETCH_LOTTERY';
export const FETCH_LOTTERY_START = 'FETCH_LOTTERY_START';
export const FETCH_LOTTERY_SUCCESS = 'FETCH_LOTTERY_SUCCESS';
export const FETCH_LOTTERY_FAIL = 'FETCH_LOTTERY_FAIL';
