export const FETCH_LOTTERY_REQUEST = 'FETCH_LOTTERY_REQUEST';
export const FETCH_LOTTERY_LOADING = 'FETCH_LOTTERY_LOADING';
export const LOAD_LOTTERY_SAGA = 'LOAD_LOTTERY_SAGA';
export const FETCH_LOTTERY_FAIL = 'FETCH_LOTTERY_FAIL';
